<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class MarketplaceThemesSeeder extends Seeder
{
    public function run()
    {
        $this->db->query('SET FOREIGN_KEY_CHECKS=0');
        $this->db->table('marketplace_themes')->truncate();
        $this->db->query('SET FOREIGN_KEY_CHECKS=1');

        $data = [
            [
                'id'           => '550e8400-e29b-41d4-a716-446655440010',
                'name'         => 'ocean-breeze',
                'display_name' => 'Ocean Breeze',
                'description'  => 'A refreshing light theme inspired by the open sea. Soft teals and ocean blues create a calm, productive workspace that\'s easy on the eyes during long work sessions.',
                'author'       => 'ThemeForge',
                'version'      => '1.2.0',
                'thumbnail_url' => null,
                'download_url' => '/themes/ocean-breeze.css',
                'price'        => 0,
                'is_published' => true,
                'metadata'     => json_encode([
                    'tags'   => ['light', 'blue', 'calm', 'minimal'],
                    'colors' => [
                        'Primary'    => '#0077B6',
                        'Secondary'  => '#00B4D8',
                        'Background' => '#E0F4FF',
                        'Surface'    => '#FFFFFF',
                        'Text'       => '#1A2B3C',
                        'Accent'     => '#48CAE4',
                    ],
                    'vars' => [
                        '--bg'                 => '#E0F4FF',
                        '--surface'            => '#FFFFFF',
                        '--surface-strong'     => '#FFFFFF',
                        '--surface-muted'      => '#F0F9FF',
                        '--border'             => '#BAE0F2',
                        '--line'               => '#90C8E0',
                        '--text'               => '#1A2B3C',
                        '--text-muted'         => '#4A6B7A',
                        '--text-strong'        => '#0D1B26',
                        '--accent'             => '#0077B6',
                        '--accent-text'        => '#FFFFFF',
                        '--accent-soft'        => '#CCE9F5',
                        '--sidebar-bg'         => '#FFFFFF',
                        '--sidebar-border'     => '#BAE0F2',
                        '--sidebar-text'       => '#1A2B3C',
                        '--sidebar-text-muted' => '#4A6B7A',
                        '--input-bg'           => '#FFFFFF',
                        '--input-border'       => '#BAE0F2',
                        '--modal-bg'           => '#FFFFFF',
                        '--chip'               => '#C8E8F0',
                        '--success'            => '#D4F0E4',
                    ],
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => '550e8400-e29b-41d4-a716-446655440011',
                'name'         => 'midnight-void',
                'display_name' => 'Midnight Void',
                'description'  => 'Deep space dark theme for night owls and late-night coders. Rich dark purples and blues with vibrant neon accents give this theme a premium, modern feel.',
                'author'       => 'ThemeForge',
                'version'      => '2.0.1',
                'thumbnail_url' => null,
                'download_url' => '/themes/midnight-void.css',
                'price'        => 0,
                'is_published' => true,
                'metadata'     => json_encode([
                    'tags'   => ['dark', 'purple', 'neon', 'night'],
                    'colors' => [
                        'Primary'    => '#7C3AED',
                        'Secondary'  => '#A78BFA',
                        'Background' => '#0D0D1A',
                        'Surface'    => '#1A1A2E',
                        'Text'       => '#E2E8F0',
                        'Accent'     => '#F472B6',
                    ],
                    'vars' => [
                        '--bg'                 => '#0D0D1A',
                        '--surface'            => '#1A1A2E',
                        '--surface-strong'     => '#222234',
                        '--surface-muted'      => '#121220',
                        '--border'             => '#2A2A44',
                        '--line'               => '#333350',
                        '--text'               => '#E2E8F0',
                        '--text-muted'         => '#94A3B8',
                        '--text-strong'        => '#F1F5F9',
                        '--accent'             => '#7C3AED',
                        '--accent-text'        => '#FFFFFF',
                        '--accent-soft'        => '#2D1A5E',
                        '--sidebar-bg'         => '#16162A',
                        '--sidebar-border'     => '#2A2A44',
                        '--sidebar-text'       => '#E2E8F0',
                        '--sidebar-text-muted' => '#94A3B8',
                        '--input-bg'           => '#0D0D1A',
                        '--input-border'       => '#2A2A44',
                        '--modal-bg'           => '#1A1A2E',
                        '--chip'               => '#2A2A44',
                        '--success'            => '#0D2A1A',
                    ],
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => '550e8400-e29b-41d4-a716-446655440012',
                'name'         => 'forest-grove',
                'display_name' => 'Forest Grove',
                'description'  => 'Earthy greens and warm neutrals bring the tranquility of a woodland retreat to your workspace. A grounding, nature-inspired theme designed for focused productivity.',
                'author'       => 'NaturePalette',
                'version'      => '1.0.5',
                'thumbnail_url' => null,
                'download_url' => '/themes/forest-grove.css',
                'price'        => 0,
                'is_published' => true,
                'metadata'     => json_encode([
                    'tags'   => ['light', 'green', 'earthy', 'nature'],
                    'colors' => [
                        'Primary'    => '#2D6A4F',
                        'Secondary'  => '#52B788',
                        'Background' => '#F0F7EE',
                        'Surface'    => '#FFFFFF',
                        'Text'       => '#1B2E22',
                        'Accent'     => '#B7E4C7',
                    ],
                    'vars' => [
                        '--bg'                 => '#F0F7EE',
                        '--surface'            => '#FFFFFF',
                        '--surface-strong'     => '#FFFFFF',
                        '--surface-muted'      => '#F5FAF4',
                        '--border'             => '#C0DACB',
                        '--line'               => '#A0C4B0',
                        '--text'               => '#1B2E22',
                        '--text-muted'         => '#527A62',
                        '--text-strong'        => '#0D1F14',
                        '--accent'             => '#2D6A4F',
                        '--accent-text'        => '#FFFFFF',
                        '--accent-soft'        => '#C0E8D4',
                        '--sidebar-bg'         => '#FFFFFF',
                        '--sidebar-border'     => '#C0DACB',
                        '--sidebar-text'       => '#1B2E22',
                        '--sidebar-text-muted' => '#527A62',
                        '--input-bg'           => '#FFFFFF',
                        '--input-border'       => '#C0DACB',
                        '--modal-bg'           => '#FFFFFF',
                        '--chip'               => '#B8E0C8',
                        '--success'            => '#CCF0DC',
                    ],
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => '550e8400-e29b-41d4-a716-446655440013',
                'name'         => 'sunset-ember',
                'display_name' => 'Sunset Ember',
                'description'  => 'Warm oranges, deep reds, and golden highlights capture the magic of a perfect sunset. This vibrant theme adds energy and warmth to every interaction.',
                'author'       => 'ChromaCraft',
                'version'      => '1.1.2',
                'thumbnail_url' => null,
                'download_url' => '/themes/sunset-ember.css',
                'price'        => 0,
                'is_published' => true,
                'metadata'     => json_encode([
                    'tags'   => ['warm', 'orange', 'vibrant', 'sunset'],
                    'colors' => [
                        'Primary'    => '#D62828',
                        'Secondary'  => '#F77F00',
                        'Background' => '#FFF5E4',
                        'Surface'    => '#FFFFFF',
                        'Text'       => '#2D1B00',
                        'Accent'     => '#FCBF49',
                    ],
                    'vars' => [
                        '--bg'                 => '#FFF5E4',
                        '--surface'            => '#FFFFFF',
                        '--surface-strong'     => '#FFFFFF',
                        '--surface-muted'      => '#FFF8F0',
                        '--border'             => '#F0D0A8',
                        '--line'               => '#E0B880',
                        '--text'               => '#2D1B00',
                        '--text-muted'         => '#8A6040',
                        '--text-strong'        => '#1A0A00',
                        '--accent'             => '#D62828',
                        '--accent-text'        => '#FFFFFF',
                        '--accent-soft'        => '#FFE0CC',
                        '--sidebar-bg'         => '#FFFFFF',
                        '--sidebar-border'     => '#F0D0A8',
                        '--sidebar-text'       => '#2D1B00',
                        '--sidebar-text-muted' => '#8A6040',
                        '--input-bg'           => '#FFFFFF',
                        '--input-border'       => '#F0D0A8',
                        '--modal-bg'           => '#FFFFFF',
                        '--chip'               => '#F8D8B0',
                        '--success'            => '#DDFADC',
                    ],
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => '550e8400-e29b-41d4-a716-446655440014',
                'name'         => 'arctic-frost',
                'display_name' => 'Arctic Frost',
                'description'  => 'Ultra-clean whites and icy blues inspired by frozen tundras. A minimalist theme that maximises clarity and focus with crisp contrast and breathable spacing.',
                'author'       => 'MinimalStudio',
                'version'      => '3.0.0',
                'thumbnail_url' => null,
                'download_url' => '/themes/arctic-frost.css',
                'price'        => 0,
                'is_published' => true,
                'metadata'     => json_encode([
                    'tags'   => ['light', 'minimal', 'clean', 'ice'],
                    'colors' => [
                        'Primary'    => '#2176AE',
                        'Secondary'  => '#57C4E5',
                        'Background' => '#F8FBFF',
                        'Surface'    => '#FFFFFF',
                        'Text'       => '#1C2B3A',
                        'Accent'     => '#A8DADC',
                    ],
                    'vars' => [
                        '--bg'                 => '#F8FBFF',
                        '--surface'            => '#FFFFFF',
                        '--surface-strong'     => '#FFFFFF',
                        '--surface-muted'      => '#F0F5FC',
                        '--border'             => '#C0D4E8',
                        '--line'               => '#A0BCDA',
                        '--text'               => '#1C2B3A',
                        '--text-muted'         => '#4E6478',
                        '--text-strong'        => '#0D1B2A',
                        '--accent'             => '#2176AE',
                        '--accent-text'        => '#FFFFFF',
                        '--accent-soft'        => '#CCE0F0',
                        '--sidebar-bg'         => '#FFFFFF',
                        '--sidebar-border'     => '#C0D4E8',
                        '--sidebar-text'       => '#1C2B3A',
                        '--sidebar-text-muted' => '#4E6478',
                        '--input-bg'           => '#FFFFFF',
                        '--input-border'       => '#C0D4E8',
                        '--modal-bg'           => '#FFFFFF',
                        '--chip'               => '#B8D4E8',
                        '--success'            => '#D4F0E4',
                    ],
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => '550e8400-e29b-41d4-a716-446655440015',
                'name'         => 'obsidian-rose',
                'display_name' => 'Obsidian Rose',
                'description'  => 'A sophisticated dark theme blending deep charcoal blacks with rose gold accents. Elegant and bold, this theme is built for those who want style without sacrificing readability.',
                'author'       => 'ChromaCraft',
                'version'      => '1.3.0',
                'thumbnail_url' => null,
                'download_url' => '/themes/obsidian-rose.css',
                'price'        => 0,
                'is_published' => true,
                'metadata'     => json_encode([
                    'tags'   => ['dark', 'elegant', 'rose', 'premium'],
                    'colors' => [
                        'Primary'    => '#C9184A',
                        'Secondary'  => '#FF4D6D',
                        'Background' => '#0A0A0F',
                        'Surface'    => '#1C1C28',
                        'Text'       => '#F1E3E4',
                        'Accent'     => '#B5838D',
                    ],
                    'vars' => [
                        '--bg'                 => '#0A0A0F',
                        '--surface'            => '#1C1C28',
                        '--surface-strong'     => '#242430',
                        '--surface-muted'      => '#14141E',
                        '--border'             => '#2A2A38',
                        '--line'               => '#383848',
                        '--text'               => '#F1E3E4',
                        '--text-muted'         => '#B5939A',
                        '--text-strong'        => '#FAF0F1',
                        '--accent'             => '#C9184A',
                        '--accent-text'        => '#FFFFFF',
                        '--accent-soft'        => '#3D0A1A',
                        '--sidebar-bg'         => '#161620',
                        '--sidebar-border'     => '#2A2A38',
                        '--sidebar-text'       => '#F1E3E4',
                        '--sidebar-text-muted' => '#B5939A',
                        '--input-bg'           => '#0A0A0F',
                        '--input-border'       => '#2A2A38',
                        '--modal-bg'           => '#1C1C28',
                        '--chip'               => '#2A2030',
                        '--success'            => '#0A2016',
                    ],
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('marketplace_themes')->insertBatch($data);
    }
}
